### ISSUE TITLE
Debian fails admin network config after install

### ISSUE THREAD

**Issue by sjensen** [digitalrebar/core#669]
Debian installs correctly and reboots and re-joins however fails in the first chef run with the following error

[2015-06-15T12:13:01-05:00] INFO: Storing updated cookbooks/utils/chefignore in the cache.
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB1be98453-aca51ccb"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VB1be98453-aca51ccb"]
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB1be98453-aca51ccb"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VB1be98453-aca51ccb"]
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBb5850d13-0a38600c"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VBb5850d13-0a38600c"]
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBb5850d13-0a38600c"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VBb5850d13-0a38600c"]
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBf1d4a5b4-fd7999df"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VBf1d4a5b4-fd7999df"]
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBf1d4a5b4-fd7999df"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VBf1d4a5b4-fd7999df"]
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB99c99cfb-aa3b9dd3"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VB99c99cfb-aa3b9dd3"]
[2015-06-15T12:13:01-05:00] INFO: [1, "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB99c99cfb-aa3b9dd3"]
[2015-06-15T12:13:01-05:00] INFO: [0, "/dev/disk/by-id/ata-VBOX_HARDDISK_VB99c99cfb-aa3b9dd3"]
[2015-06-15T12:13:01-05:00] INFO: Current disks: [{"ids"=>["/dev/disk/by-id/ata-VBOX_CD-ROM_VB2-01700376"], "unique_name"=>"/dev/disk/by-id/ata-VBOX_CD-ROM_VB2-01700376", "path"=>"/sys/devices/pci0000:00/0000:00:01.1/host1/target1:0:0/1:0:0:0/block/sr0", "usb"=>false, "readonly"=>false, "ssd"=>false, "size"=>1073741312, "removable"=>true, "virtual"=>false, "partitioned"=>false, "held"=>false, "formatted"=>false, "used"=>false}, {"ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VB1be98453-aca51ccb", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB1be98453-aca51ccb"], "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VB1be98453-aca51ccb", "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host2/target2:0:0/2:0:0:0/block/sda", "usb"=>false, "readonly"=>false, "ssd"=>true, "size"=>21474836480, "removable"=>false, "virtual"=>false, "partitioned"=>true, "held"=>false, "formatted"=>false, "used"=>true}, {"ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VBb5850d13-0a38600c", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBb5850d13-0a38600c"], "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VBb5850d13-0a38600c", "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host3/target3:0:0/3:0:0:0/block/sdb", "usb"=>false, "readonly"=>false, "ssd"=>true, "size"=>8589934592, "removable"=>false, "virtual"=>false, "partitioned"=>false, "held"=>false, "formatted"=>false, "used"=>false}, {"ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VBf1d4a5b4-fd7999df", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBf1d4a5b4-fd7999df"], "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VBf1d4a5b4-fd7999df", "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host4/target4:0:0/4:0:0:0/block/sdc", "usb"=>false, "readonly"=>false, "ssd"=>false, "size"=>8589934592, "removable"=>false, "virtual"=>false, "partitioned"=>false, "held"=>false, "formatted"=>false, "used"=>false}, {"ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VB99c99cfb-aa3b9dd3", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB99c99cfb-aa3b9dd3"], "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VB99c99cfb-aa3b9dd3", "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host5/target5:0:0/5:0:0:0/block/sdd", "usb"=>false, "readonly"=>false, "ssd"=>false, "size"=>8589934592, "removable"=>false, "virtual"=>false, "partitioned"=>false, "held"=>false, "formatted"=>false, "used"=>false}]
[2015-06-15T12:13:01-05:00] INFO: Recorded disks: [{"formatted"=>false, "held"=>false, "ids"=>[], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:01.1/host1/target1:0:0/1:0:0:0/block/sr0", "readonly"=>false, "removable"=>true, "size"=>1073741312.0, "ssd"=>false, "unique_name"=>"/dev/sr0", "usb"=>false, "used"=>false, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VB1be98453-aca51ccb", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB1be98453-aca51ccb"], "partitioned"=>true, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host2/target2:0:0/2:0:0:0/block/sda", "readonly"=>false, "removable"=>false, "size"=>21474836480.0, "ssd"=>true, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VB1be98453-aca51ccb", "usb"=>false, "used"=>true, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VBb5850d13-0a38600c", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBb5850d13-0a38600c"], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host3/target3:0:0/3:0:0:0/block/sdb", "readonly"=>false, "removable"=>false, "size"=>8589934592.0, "ssd"=>true, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VBb5850d13-0a38600c", "usb"=>false, "used"=>false, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VBf1d4a5b4-fd7999df", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBf1d4a5b4-fd7999df"], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host4/target4:0:0/4:0:0:0/block/sdc", "readonly"=>false, "removable"=>false, "size"=>8589934592.0, "ssd"=>false, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VBf1d4a5b4-fd7999df", "usb"=>false, "used"=>false, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VB99c99cfb-aa3b9dd3", "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB99c99cfb-aa3b9dd3"], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/host5/target5:0:0/5:0:0:0/block/sdd", "readonly"=>false, "removable"=>false, "size"=>8589934592.0, "ssd"=>false, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VB99c99cfb-aa3b9dd3", "usb"=>false, "used"=>false, "virtual"=>false}]
[2015-06-15T12:13:01-05:00] ERROR: Running exception handlers
[2015-06-15T12:13:01-05:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2015-06-15T12:13:01-05:00] ERROR: Exception handlers complete
[2015-06-15T12:13:01-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-06-15T12:13:01-05:00] FATAL: NoMethodError: undefined method `ids' for #<Mash:0x00000002d6f040>

Err:Warning: Permanently added '192.168.124.84' (RSA) to the list of known hosts.

Backtrace:
/opt/opencrowbar/core/rails/app/models/barclamp_chef/jig.rb:71:in `run'
/opt/opencrowbar/core/rails/app/models/run.rb:67:in `run'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/job.rb:15:in `_run'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/job.rb:99:in `block in work'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/adapters/active_record.rb:5:in `block in checkout'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/adapters/active_record.rb:34:in `checkout_activerecord_adapter'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/adapters/active_record.rb:5:in `checkout'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/job.rb:82:in `work'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/worker.rb:78:in `block in work_loop'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/worker.rb:73:in `loop'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/worker.rb:73:in `work_loop'
/var/cache/crowbar/gems/ruby/2.1.0/gems/que-0.10.0/lib/que/worker.rb:17:in `block in initialize'

**Comment by sjensen** [comment]
reoccurs on a retry

[2015-06-15T13:44:18-05:00] FATAL: NoMethodError: undefined method `ids' for #<Mash:0x000000027336b8>

**Comment by VictorLowther** [comment]
Should be fixed by #670

**Comment by StephenTames** [comment]
@galthaus This appears to be a resolved issue.

**Comment by galthaus** [comment]
fixed
